repos:
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.3" # or any later Vulture version
    hooks:
      - id: vulture

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [pre-commit]
        language: system
        entry: poetry run mypy
        types: [python]
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
        args: [--check]

  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.6"
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
