server:
  host: 0.0.0.0
  port: 8000
  reload: True
  workers: 1
  root_path: "/api"
  root_path_in_servers: True
  prefix: ""
  allow_origins: ["*"]
  allow_credentials: True
  allow_methods: ["*"]
  allow_headers: ["*"]
db:
  log: False
  pool_size: 12
  max_overflow: 10
jwt:
  access_token_lifetime: 60
  refresh_token_lifetime: 90
permissions:
  model: model.conf
  policy: policy.csv
  log: False
