name: Blocking Issues

on:
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened]
  pull_request_target:
    types: [opened, edited, closed, reopened]

jobs:
  blocking_issues:
    permissions:
      checks: write
      issues: write
      pull-requests: write
    uses: ITSolve-dev/BackOffice.GitHubActions/.github/workflows/blocking-issues.yml@main
