name: CD
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: ITSolve-dev/BackOffice.GitHubActions/.github/workflows/build-and-push.yml@main
    permissions:
      packages: write
      contents: write

  deploy:
    needs: [build]
    uses: ITSolve-dev/BackOffice.GitHubActions/.github/workflows/dokploy.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      app-id: ${{ secrets.DOKPLOY_PROD_APPLICATION_ID }}
      url: ${{ secrets.DOKPLOY_URL }}
      token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
    permissions:
      packages: write
      contents: read
      deployments: write

  migrations:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      DATABASE__URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Poetry install
        uses: ITSolve-dev/BackOffice.GitHubActions/.github/actions/poetry-install@main
        with:
          python: 3.13.1
      - name: Migrations
        run: poetry run alembic upgrade head
