name: CD
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: ITSolve-dev/BackOffice.GitHubActions/.github/workflows/build-and-push.yml@main
    permissions:
      packages: write
      contents: write

  deploy:
    needs: [build]
    uses: ITSolve-dev/BackOffice.GitHubActions/.github/workflows/dokploy.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      app-id: ${{ secrets.DOKPLOY_PROD_APPLICATION_ID }}
      url: ${{ secrets.DOKPLOY_URL }}
      token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
    permissions:
      packages: write
      contents: read
      deployments: write
