name: CD
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    uses: ITSolve-dev/BackOffice.GitHubActions/.github/workflows/deploy/build-and-push.yml@main
    with:
      deployments: false
    permissions:
      packages: write
      contents: write
      deployments: write
  deploy:
    uses: ITSolve-dev/BackOffice.GitHubActions/.github/workflows/deploy/dokploy.yml@main
    with:
      url: ${{ secrets.DOKPLOY_URL }}
      token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
      app-id: ${{ secrets.DOKPLOY_PROD_APPLICATION_ID }}
    permissions:
      packages: write
      contents: read
      deployments: write
