name: Pull Request Labeler
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    uses: ITSolve-dev/BackOffice.GitHubActions/.github/workflows/labeler.yml@main
